/*
===============================================================================
3. Customer & Product Insights
===============================================================================
Purpose:
    - To understand who drives sales and what sells: ranking top and bottom
      performers, sizing sales across categories, grouping customers and
      products into segments, and measuring how each category contributes
      to the whole.

Contents:
    - Magnitude Analysis      : Compare sales magnitude across dimensions.
    - Ranking Analysis        : Rank top and bottom customers, products, and categories.
    - Data Segmentation       : Segment customers and products into meaningful groups.
    - Part-to-Whole Analysis  : Measure each category's contribution to total sales.

SQL Functions Used:
    - Aggregate Functions   : SUM(), COUNT(), AVG()
    - Ranking Functions     : RANK(), ROW_NUMBER(), TOP
    - Window Functions      : SUM() OVER(), CASE WHEN with aggregation

Tables Used:
    - gold.fact_sales
    - gold.dim_customers
    - gold.dim_products
===============================================================================
*/

-- 08_magnitude_analysis.sql — Compare sales magnitude across dimensions.
-- Find total customers by countries
SELECT
country,
COUNT(customer_id)
FROM gold.dim_customers AS total_customers
GROUP BY country
ORDER BY COUNT(customer_id) DESC;

-- Find total customers by gender
SELECT
gender,
COUNT(customer_id) AS total_customers
FROM gold.dim_customers 
GROUP BY gender
ORDER BY COUNT(customer_id) DESC;

-- Find total products by category
SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products 
GROUP BY category
ORDER BY COUNT(product_key) DESC;

-- What is the average costs in each category?
SELECT 
category,
AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;

-- What is the total revenue generated for each category?
SELECT 
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY category
ORDER BY total_revenue DESC;


-- What is the total revenue generated by each customer?
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries (total quantity/countries)
SELECT 
c.country,
SUM(f.sales_quantity) AS total_quantity
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY
c.country
ORDER BY total_quantity DESC;

-- 09_ranking_analysis.sql — Rank top and bottom customers, products, and categories.
-- Which 5 products generate the highest revenue?

SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

-- Using window function
SELECT *
FROM(
	SELECT
	p.product_name,
	SUM(f.sales_amount) AS total_revenue,
	ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON f.product_key = p.product_key
	GROUP BY p.product_name)t
WHERE rank_products <= 5


-- Which 5 worst-performing products generate in terms of sales?

SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC


-- Find the top 10 customers who have generated the highest revenuw
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC


-- 10_data_segmentation.sql — Segment customers and products into meaningful groups.

/*Segment products into cost ranges and 
count how many products fall into each segment*/
WITH product_segment AS (
SELECT
product_key,
product_name,
cost,
CASE WHEN cost < 100 THEN 'Below 100'
     WHEN cost BETWEEN 100 AND 500 THEN '100-500'
     WHEN COST BETWEEN 500 AND 1000 THEN '500-1000'
     ELSE 'Above 1000'
END cost_range
FROM gold.dim_products
)

SELECT 
cost_range,
count(product_key) AS total_products
FROM product_segment
GROUP BY cost_range
ORDER BY total_products DESC;

-- 11_part_to_whole_analysis.sql — Measure each category's contribution to total sales.
-- Which categories contribute the most to overall sales?
WITH category_sales AS(
SELECT
category,
SUM(sales_amount) total_sales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY category)

SELECT
category,
total_sales,
SUM(total_sales) OVER() overall_sales,
CONCAT(ROUND((CAST(total_sales AS FLOAT)/SUM(total_sales) OVER())*100, 2), '%') AS percentage_of_total
FROM category_sales
ORDER BY total_sales DESC;
